name: Auto Label and Add to Project

on:
  issues:
    types: [opened]

jobs:
  auto-label:
    runs-on: ubuntu-latest
    steps:
      - name: Add label to issue
        uses: actions/labeler@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

  add-to-project:
    runs-on: ubuntu-latest
    steps:
      - name: Add issue to project
        uses: actions/add-to-project@v1
        with:
          project-url: https://github.com/users/ningning12138/projects/1
          column-name: Todo
          github-token: ${{ secrets.GITHUB_TOKEN }}
          labeled: bug, enhancement
          label-operator: OR
